name: asadel
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  get: 4.6.6
  intl: ^0.19.0
  image_cropper: ^8.0.1
  get_storage: ^2.1.1
  flutter_screenutil: ^5.6.0
  fluttertoast: ^8.2.6
  image_picker: ^1.1.2
  url_launcher: ^6.1.11
  device_info_plus: ^8.0.0
  firebase_messaging: ^15.0.4
  firebase_core: ^3.3.0
  flutter_local_notifications: ^17.2.2
  animated_toggle_switch: ^0.8.3
  flutter_launcher_icons: ^0.13.1
  shimmer: ^3.0.0
  in_app_notification: ^1.1.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - images/
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "images/vmm_logo.png"

